### ISSUE TITLE
StompClient disconnectCompletable over OkHTTP and JWS doesn't really waits for a disconnection

### ISSUE THREAD

**Issue by UbivisDev** [NaikSoftware/StompProtocolAndroid#104]
While trying to reconnect to a JSW StompClient, the disconnectCompletable makes a _fromAction_() call to the non blocking version of org.java_websocket.client.WebSocketClient close in the AbstractConnectionProvider implementation of disconnect(). This tricks the StompClient into assuming its safe to connects once again, which yields IllegalStateException: "Already have connection to web socket". I think changing the implementation of AbstractConnectionProvider::rawDisconnect from close() to closeBlocking() might be enough. There's something similar happening with the OkHTTP implementation, but I could not track it yet.

**Comment by UbivisDev** [comment]
Looks like the OkHTTP have the same issue. I forked and made some changes on these implementations, but I want to discuss the issue here before making a pull request. I'm currently testing these modification with my use cases, and currently its working great.

**Comment by forresthopkinsa** [comment]
As long as the blocking method is _within a completable_ I think it's fine

**Comment by UbivisDev** [comment]
The way AbstractConnectionProvider was implemented, it always encapsulates calls to rawDisconnect (which is protected) in a completable with _fromAction_() and return it in the disconnect() interface function, so I think it's well encapsulated within a completable.

**Comment by NaikSoftware** [comment]
@UbivisDev thanks for pull request. Changes in JWS approved, but disconnect in OKHTTP implementation fixed by other way in latest release (1.5.4)

**Comment by UbivisDev** [comment]
@NaikSoftware Well, my implementation for the OkHttp rawClose wasn't very concise, so I think it's fine. Only, I'm still having issues with _IllegalStateException: Not connected yet_ while reconnecting in v1.5.4. Are you sure the method is really blocking until close completion?
