### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by nanhuaqq** [NaikSoftware/StompProtocolAndroid#96]
version 1.4.4
StompClient.java 
topic() method ,
`if (subscriber.isCancelled()) {
                               setIterator.remove();
                               if (set.size() < 1) {
                                   mapIterator.remove();
                                   unsubscribePath(destinationUrl).subscribe();
                               }
                           }`
I think it should be  `if(!subscriber.isCancelled())`

**Comment by forresthopkinsa** [comment]
**Why** do you post code that's so unreadable? Inform yourself on how to post code blocks on Github, please. It's frustrating to see this all over the place. This is impossible to read.

`topic` method:

``` java
public Flowable<StompMessage> topic(String destinationPath, List<StompHeader> headerList) {
   return Flowable.<StompMessage>create(emitter -> {
       synchronized (mEmitters) {
           Set<FlowableEmitter<? super StompMessage>> emittersSet = mEmitters.get(destinationPath);
           if (emittersSet == null) {
               emittersSet = new HashSet<>();
               mEmitters.put(destinationPath, emittersSet);
               subscribePath(destinationPath, headerList).subscribe();
           }
           emittersSet.add(emitter);
       }
   }, BackpressureStrategy.BUFFER)
       .doOnCancel(() -> {
           synchronized (mEmitters) {
               Iterator<String> mapIterator = mEmitters.keySet().iterator();
               while (mapIterator.hasNext()) {
                   String destinationUrl = mapIterator.next();
                   Set<FlowableEmitter<? super StompMessage>> set = mEmitters.get(destinationUrl);
                   Iterator<FlowableEmitter<? super StompMessage>> setIterator = set.iterator();
                   while (setIterator.hasNext()) {
                       FlowableEmitter<? super StompMessage> subscriber = setIterator.next();
                       if (subscriber.isCancelled()) {
                           setIterator.remove();
                           if (set.size() < 1) {
                               mapIterator.remove();
                               unsubscribePath(destinationUrl).subscribe();
                           }
                       }
                   }
               }
           }
       });
}
```

Excerpt:

``` java
while (setIterator.hasNext()) {
   FlowableEmitter<? super StompMessage> subscriber = setIterator.next();
   if (subscriber.isCancelled()) {     // you're suggesting that this should be inverted
       setIterator.remove();
       if (set.size() < 1) {
           mapIterator.remove();
           unsubscribePath(destinationUrl).subscribe();
       }
   }
}
```

Okay, now we have something we can work with

**Comment by forresthopkinsa** [comment]
I'm not understanding why you think that should be inverted. The code here is flushing topics with no more subscribers.

`if` the subscriber is cancelled
`then` remove it from the topic's subscriber set, and
`if` that makes the subscriber set empty,
`then` remove the topic from the map

at least, that's what it looks like is happening here, I can't recall for certain

**Comment by NaikSoftware** [comment]
Attention! Memory leaks really exists in this code - remove emitters in doOnCancelled its bad idea :) 
But fixed in release **1.4.5**

**Comment by forresthopkinsa** [comment]
I agree; in fact, I think that this Rx code deserves a full rewrite (hence my fork), but I still don't understand what @nanhuaqq was suggesting. Is that what he was saying? I didn't obtain that from his post at all.
